"""
CivicPulse — India Election Calendar Service
============================================
Localized for Indian Time Zones (IST) and ECI-specific milestones.
"""

from __future__ import annotations
import json
import logging
import urllib.parse
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

class CalendarService:
    """
    Handles election reminders localized for India.
    Uses 'Asia/Kolkata' as the default Timezone.
    """

    def __init__(self, access_token: str | None = None) -> None:
        self.access_token = access_token
        self.timezone = "Asia/Kolkata"

    def generate_reminder_links(self, election_data: dict) -> list[dict]:
        """Generate a list of Google Calendar links for Indian users."""
        events = self._build_india_reminder_events(election_data)
        links = []
        for event in events:
            date_str = event.get("_date", "")
            link = self.generate_gcal_link(
                title=event["summary"].replace("🗳️ CivicPulse: ", ""),
                date_str=date_str,
                description=event.get("description", ""),
            )
            links.append({"title": event["summary"], "date": date_str, "link": link})
        return links

    def generate_gcal_link(self, title: str, date_str: str, description: str = "") -> str:
        """Fallback link generator - No API Key required for the user."""
        try:
            dt = datetime.strptime(self._normalize_date(date_str), "%Y-%m-%d")
            start = dt.strftime("%Y%m%d")
            # All-day events in GCal links need the end date to be the day after
            end = (dt + timedelta(days=1)).strftime("%Y%m%d")
        except Exception:
            return "#"

        params = {
            "action": "TEMPLATE",
            "text": f"🗳️ {title}",
            "dates": f"{start}/{end}",
            "details": f"{description}\n\nGenerated by CivicPulse India",
            "ctz": self.timezone
        }
        return "https://calendar.google.com/calendar/render?" + urllib.parse.urlencode(params)

    # ── Private Helpers ───────────────────────────────────────────────────────

    def _build_india_reminder_events(self, election_data: dict) -> list[dict]:
        events = []
        state_name = election_data.get("jurisdiction", "India")

        # 1. Poll Day (Election Day)
        if poll_day := election_data.get("poll_date") or election_data.get("next_election_date"):
            events.append(self._build_event(
                summary=f"VOTE: {state_name} Assembly Election",
                date_str=poll_day,
                description=f"Poll Day for {state_name}. Carry your Voter ID or Aadhaar. No mobile phones allowed in the booth!",
                color_id="10" # Green
            ))

            # 2. Dry Day Reminder (48 hours before poll)
            try:
                poll_dt = datetime.strptime(self._normalize_date(poll_day), "%Y-%m-%d")
                dry_day = (poll_dt - timedelta(days=1)).strftime("%Y-%m-%d")
                events.append(self._build_event(
                    summary="Dry Day Starts (Pre-Poll)",
                    date_str=dry_day,
                    description="48-hour quiet period starts. No liquor sales or public campaigning permitted.",
                    color_id="6" # Orange/Red
                ))
            except: pass

        # 3. Counting Day
        if count_day := election_data.get("counting_day"):
            events.append(self._build_event(
                summary=f"Election Results: {state_name}",
                date_str=count_day,
                description="Counting of votes begins today at 8:00 AM. Check news for real-time updates.",
                color_id="9" # Blue
            ))

        return events

    def _build_event(self, summary: str, date_str: str, description: str, color_id: str = "10") -> dict:
        norm_date = self._normalize_date(date_str)
        return {
            "_date": norm_date,
            "summary": f"🗳️ CivicPulse: {summary}",
            "description": description,
            "colorId": color_id,
            "start": {"date": norm_date},
            "end": {"date": norm_date}
        }

    def _normalize_date(self, date_str: str) -> str:
        """Handles Indian date formats like 'April 23, 2026'."""
        if not date_str or "Varies" in date_str or "Phase" in date_str:
            return datetime.now().strftime("%Y-%m-%d")
            
        for fmt in ("%Y-%m-%d", "%B %d, %Y", "%d %B %Y", "%m/%d/%Y"):
            try:
                return datetime.strptime(date_str, fmt).strftime("%Y-%m-%d")
            except ValueError:
                continue
        return date_str