"""
CivicPulse — India Election Calendar Service
============================================
Localized for Indian Time Zones (IST) and ECI-specific milestones.
"""

from __future__ import annotations
import logging
import urllib.parse
from datetime import datetime, timedelta

from config.settings import INDIA

logger = logging.getLogger(__name__)


class CalendarService:
    """
    Handles election reminders localized for India.
    Uses Asia/Kolkata as the default timezone (from settings — no magic strings).
    """

    def __init__(self, access_token: str | None = None) -> None:
        self.access_token = access_token
        self.timezone = INDIA["TIMEZONE"]

    def generate_reminder_links(self, election_data: dict) -> list[dict]:
        """Generate a list of Google Calendar add-event links for Indian voters."""
        events = self._build_india_reminder_events(election_data)
        links: list[dict] = []
        for event in events:
            date_str = event.get("_date", "")
            link = self.generate_gcal_link(
                title=event["summary"].replace("🗳️ CivicPulse: ", ""),
                date_str=date_str,
                description=event.get("description", ""),
            )
            links.append({"title": event["summary"], "date": date_str, "link": link})
        return links

    def generate_gcal_link(
        self, title: str, date_str: str, description: str = ""
    ) -> str:
        """
        Build a Google Calendar 'add event' link — no API key required for users.
        Returns '#' if the date cannot be parsed.
        """
        normalized = self._normalize_date(date_str)
        if not normalized:
            return "#"
        try:
            dt = datetime.strptime(normalized, "%Y-%m-%d")
            start = dt.strftime("%Y%m%d")
            end = (dt + timedelta(days=1)).strftime("%Y%m%d")
        except ValueError:
            logger.warning("Could not format date '%s' for GCal link", date_str)
            return "#"

        params = {
            "action": "TEMPLATE",
            "text": f"🗳️ {title}",
            "dates": f"{start}/{end}",
            "details": f"{description}\n\nGenerated by CivicPulse India",
            "ctz": self.timezone,
        }
        return "https://calendar.google.com/calendar/render?" + urllib.parse.urlencode(params)

    # ── Private Helpers ───────────────────────────────────────────────────────

    def _build_india_reminder_events(self, election_data: dict) -> list[dict]:
        events: list[dict] = []
        state_name = election_data.get("jurisdiction", "India")

        # 1. Poll Day
        poll_day = election_data.get("poll_date") or election_data.get("next_election_date")
        if poll_day:
            events.append(self._build_event(
                summary=f"VOTE: {state_name} Assembly Election",
                date_str=poll_day,
                description=(
                    f"Poll Day for {state_name}. Carry your Voter ID or Aadhaar. "
                    "No mobile phones allowed in the booth!"
                ),
                color_id="10",
            ))

            # 2. Dry Day Reminder (day before poll)
            normalized = self._normalize_date(poll_day)
            if normalized:
                try:
                    poll_dt = datetime.strptime(normalized, "%Y-%m-%d")
                    dry_day = (poll_dt - timedelta(days=1)).strftime("%Y-%m-%d")
                    events.append(self._build_event(
                        summary="Dry Day Starts (Pre-Poll)",
                        date_str=dry_day,
                        description=(
                            "48-hour quiet period starts. "
                            "No liquor sales or public campaigning permitted."
                        ),
                        color_id="6",
                    ))
                except ValueError as exc:
                    logger.warning("Could not compute dry day from '%s': %s", poll_day, exc)

        # 3. Counting Day
        count_day = election_data.get("counting_day")
        if count_day:
            events.append(self._build_event(
                summary=f"Election Results: {state_name}",
                date_str=count_day,
                description=(
                    "Counting of votes begins today at 8:00 AM. "
                    "Check news for real-time updates."
                ),
                color_id="9",
            ))

        return events

    def _build_event(
        self,
        summary: str,
        date_str: str,
        description: str,
        color_id: str = "10",
    ) -> dict:
        norm_date = self._normalize_date(date_str) or date_str
        return {
            "_date": norm_date,
            "summary": f"🗳️ CivicPulse: {summary}",
            "description": description,
            "colorId": color_id,
            "start": {"date": norm_date},
            "end": {"date": norm_date},
        }

    def _normalize_date(self, date_str: str) -> str | None:
        """
        Convert various Indian date formats to ISO YYYY-MM-DD.
        Returns None if the input is absent, ambiguous, or unparseable
        (instead of silently returning today's date).
        """
        if not date_str:
            return None
        if any(word in date_str for word in ("Varies", "Phase", "Ongoing", "TBA", "Expected")):
            return None

        for fmt in ("%Y-%m-%d", "%B %d, %Y", "%d %B %Y", "%m/%d/%Y", "%d-%m-%Y", "%d/%m/%Y"):
            try:
                return datetime.strptime(date_str.strip(), fmt).strftime("%Y-%m-%d")
            except ValueError:
                continue

        logger.warning("_normalize_date: unrecognized format '%s'", date_str)
        return None
